#!/bin/bash

set -o errexit

set -o pipefail

set -o nounset

mysql_ready(){
python << END
import sys
import mysql.connector

try:
    mysql.connector.connect(
        user="${MYSQL_DB_USER}",
        password="${MYSQL_DB_PASSWORD}",
        host="${MYSQL_DB_HOST}",
        database="${MYSQL_DB}",
        port="${MYSQL_DB_PORT}"
    )
except mysql.connector.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}



until mysql_ready; do
 >&2 echo "Waiting for MySQL to become available...."
 sleep 1
done 
>&2 echo "MySQL is ready!!!"

exec "$@" 