version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/local/django/DockerFile
    command: /start  
    volumes: 
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports: 
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mysql-db
    networks:
      - estate-react

  mysql-db:
    image: mysql:8.2.0
    ports: 
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_DB_USER=${MYSQL_DB_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - estate-react

networks: 
  estate-react:
    driver: bridge

volumes:
  mysql_data:
  static_volume:
  media_volume: