# Generated by Django 5.0 on 2023-12-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="isSuperuser",
            field=models.BooleanField(default=False),
        ),
    ]
