# Generated by Django 5.0 on 2023-12-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_issuperuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="isActive",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="isStaff",
            new_name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="isSuperuser",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
